version: '3'
services:
  consul:
    image: consul:1.12.3
    container_name: consul-server
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - hazelcast-net

  hazelcast1:
    image: hazelcast/hazelcast:5.0.3
    ports:
      - "5701:5701"
    networks:
      - hazelcast-net

  hazelcast2:
    image: hazelcast/hazelcast:5.0.3
    ports:
      - "5702:5701"
    networks:
      - hazelcast-net

  hazelcast3:
    image: hazelcast/hazelcast:5.0.3
    ports:
      - "5703:5701"
    networks:
      - hazelcast-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hazelcast-net

  logging_service1:
    build: ./logging_service
    ports:
      - "8001:8000"
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=logging-service
      - SERVICE_PORT=8001
    networks:
      - hazelcast-net

  logging_service2:
    build: ./logging_service
    ports:
      - "8002:8000"
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=logging-service
      - SERVICE_PORT=8002
    networks:
      - hazelcast-net

  logging_service3:
    build: ./logging_service
    ports:
      - "8003:8000"
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=logging-service
      - SERVICE_PORT=8003
    networks:
      - hazelcast-net

  facade_service:
    build: ./facade_service
    ports:
      - "8000:8000"
    depends_on:
      - logging_service1
      - logging_service2
      - logging_service3
      - rabbitmq
      - consul
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=facade-service
      - SERVICE_PORT=8000
    networks:
      - hazelcast-net

  messages_service1:
    build: ./messages_service
    ports:
      - "8004:8000"
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=messages-service
      - SERVICE_PORT=8004
    networks:
      - hazelcast-net

  messages_service2:
    build: ./messages_service
    ports:
      - "8005:8000"
    environment:
      - CONSUL_HOST=consul
      - SERVICE_NAME=messages-service
      - SERVICE_PORT=8005
    networks:
      - hazelcast-net

networks:
  hazelcast-net:
